export const USER_NAME='USER_NAME';
export const DELETE='DELETE';
export const NAME_CHANGED="NAME_CHANGED"
export const SECRETWORD="SECRETWORD"
export const GUESSEDWORD="GUESSEDWORD"
export const RESET="RESET"
export const JEST_THUNK_SPINNER="JEST_THUNK_SPINNER"
export const AXIOS_URL="AXIOS_URL"